name: Automerge PR de Carlos + Borrar Rama

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  automerge:
    if: github.actor == 'carlostoek'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pr = context.payload.pull_request;

            if (pr.mergeable_state === 'clean') {
              // Hacemos el merge
              await github.pulls.merge({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: pr.number,
                merge_method: "squash"
              });
              console.log("✅ PR fusionado automáticamente 🎉");

              // Borramos la rama remota
              const ref = `heads/${pr.head.ref}`;
              if (pr.head.ref !== 'main' && pr.head.ref !== 'master') {
                await github.git.deleteRef({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  ref: ref
                });
                console.log(`🧹 Rama '${pr.head.ref}' eliminada automáticamente.`);
              } else {
                console.log("⚠️ No se borra la rama principal (main/master).");
              }
            } else {
              console.log("⚠️ PR no mergeable por ahora ⏳");
            }
